config/routes.rb
Tienda::Application.routes.draw do
  resources :presupuestos
  resources :facturas do
    get 'summary', on: :collection
  end
  resources :albarans
  resources :users, :only => :show
  resources :user_sessions, :only => [:new, :create, :destroy]
  
  match 'login' => 'user_sessions#new', :as => :login, via: [:get, :post]
  match 'logout' => 'user_sessions#destroy', :as => :logout, via: [:get, :post]
  match 'home' => 'users#show', :as => :home, via: [:get, :post]

  root :to => 'user_sessions#new'
end

app/models/albaran.rb
class Albaran < ActiveRecord::Base
  belongs_to :cliente
  has_many :items, :as => :order, dependent: :destroy
  
  accepts_nested_attributes_for :cliente, :items
  
  validates :number, :uniqueness => true, :numericality => true
  validates :cliente, :presence => true
  
  before_validation :set_default_values
  before_save :calculate_total
  after_initialize :set_default_values
  
  IMPUESTO = GlobalConfiguration.impuesto
  MSM_INFO = [ "Carretera del Morche 200", "El Morche , Malaga  29793", "Tel. 952968184, Fax 952968184", "VICTOR HUGO DE LOS SANTOS FORNI", "N.I.F. 54234379-B"]
  
  private
  def set_default_values
    self.number||= (Albaran.maximum(:number) || 0)+1
    self.total||= 0
  end
  def calculate_total
    self.total = items.reduce(0) do |sum, item|
      sum + item.total
    end
  end
end

app/controllers/albarans_controller.rb
class AlbaransController < InvoiceController
  def invoice
    :albaran
  end
end

app/views/albarans/edit.html.haml
= render :partial => 'invoice/edit', :locals => {:invoice => :albaran, :taxes => false}

app/views/albarans/index.html.haml
:javascript
  //localize dates
  $(document).ready(function (){
    $('.date').each( function(){
      date = $.datepicker.parseDate('yy-mm-dd', $(this).text().trim());
      $(this).text($.datepicker.formatDate($.datepicker.regional['es'].dateFormat, date));
    });
   });
  
#albaran  
  %h1 Listado de Albaranes
  .todos
    %table
      %tr
        %th Numero
        %th Fecha
        %th Cliente
        %th{:class => 'todos_menu'}
        %th{:class => 'todos_menu'}
        %th{:class => 'todos_menu'}

      - @albarans.each do |albaran|
        %tr
          %td
            = albaran.number
          %td.date
            = albaran.created_at
          %td
            = albaran.cliente
          %td{:class => 'todos_menu'}
            = link_to 'Ver', albaran
          %td{:class => 'todos_menu'}
            = link_to 'Editar', edit_albaran_path(albaran)
          %td{:class => 'todos_menu'}
            = link_to 'Eliminar', albaran, :confirm => '¿Estas seguro?', :method => :delete
  .piepagina
    = link_to 'Nuevo Albaran', new_albaran_path

app/views/albarans/new.html.haml
= render :partial => 'invoice/new', :locals => {:invoice => :albaran, :title => 'Nuevo Albaran', :taxes => false}

app/views/albarans/show.html.haml
= render :partial => 'invoice/show', :locals => {:invoice => :albaran, :taxes => false}