config/routes.rb
Tienda::Application.routes.draw do
  resources :presupuestos
  resources :facturas do
    get 'summary', on: :collection
  end
  resources :albarans
  resources :users, :only => :show
  resources :user_sessions, :only => [:new, :create, :destroy]
  
  match 'login' => 'user_sessions#new', :as => :login, via: [:get, :post]
  match 'logout' => 'user_sessions#destroy', :as => :logout, via: [:get, :post]
  match 'home' => 'users#show', :as => :home, via: [:get, :post]

  root :to => 'user_sessions#new'
end

app/models/presupuesto.rb
class Presupuesto < ActiveRecord::Base
  belongs_to :cliente
  has_many :items, :as => :order, dependent: :destroy
  
  accepts_nested_attributes_for :cliente, :items
  
  validates :number, :uniqueness => true, :numericality => true
  validates :cliente, :presence => true
  
  before_validation :set_default_values
  before_save :calculate_subtotal
  after_initialize :set_default_values
  
  IMPUESTO = GlobalConfiguration.impuesto
  MSM_INFO = [ "Carretera del Morche 200", "El Morche , Malaga  29793", "Tel. 952968184, Fax 952968184", "VICTOR HUGO DE LOS SANTOS FORNI", "N.I.F. 54234379-B"]
  
  def total
    total = subtotal + impuesto_subtotal
  end
  
  def impuesto_subtotal
    (subtotal*impuesto/100.0).to_d.round(2, BigDecimal::ROUND_UP)
  end
  
  private
  def set_default_values
    self.number||= (Presupuesto.maximum(:number) || 0)+1
    self.subtotal||= 0
    self.impuesto||=IMPUESTO
  end
  def calculate_subtotal
    self.subtotal = items.reduce(0) do |sum, item|
      sum + item.total
    end
  end
end

app/controllers/presupuestos_controller.rb
class PresupuestosController < InvoiceController
  def invoice
    :presupuesto
  end
end

app/helpers/presupuestos_helper.rb
module PresupuestosHelper
end

app/views/presupuestos/edit.html.haml
= render :partial => 'invoice/edit', :locals => {:invoice => :presupuesto}

app/views/presupuestos/index.html.haml
:javascript
  //localize dates
  $(document).ready(function (){
    $('.date').each( function(){
      date = $.datepicker.parseDate('yy-mm-dd', $(this).text().trim());
      $(this).text($.datepicker.formatDate($.datepicker.regional['es'].dateFormat, date));
    });
   });
#presupuesto  
  %h1 Listado de Presupuestos
  .todos
    %table
      %tr
        %th Numero
        %th Fecha
        %th Cliente
        %th{:class => 'todos_menu'}
        %th{:class => 'todos_menu'}
        %th{:class => 'todos_menu'}

      - @presupuestos.each do |presupuesto|
        %tr
          %td
            = presupuesto.number
          %td.date
            = presupuesto.created_at
          %td
            = presupuesto.cliente
          %td{:class => 'todos_menu'} 
            = link_to 'Ver', presupuesto
          %td{:class => 'todos_menu'} 
            = link_to 'Editar', edit_presupuesto_path(presupuesto)
          %td{:class => 'todos_menu'} 
            = link_to 'Eliminar', presupuesto, :confirm => '¿Estas seguro?', :method => :delete
  .piepagina
    = link_to 'Nuevo presupuesto', new_presupuesto_path

app/views/presupuestos/new.html.haml
= render :partial => 'invoice/new', :locals => {:invoice => :presupuesto, :title => 'Nuevo Presupuesto'}

app/views/presupuestos/show.html.haml
= render :partial => 'invoice/show', :locals => {:invoice => :presupuesto}