config/routes.rb
Tienda::Application.routes.draw do
  resources :presupuestos
  resources :facturas do
    get 'summary', on: :collection
  end
  resources :albarans
  resources :users, :only => :show
  resources :user_sessions, :only => [:new, :create, :destroy]
  
  match 'login' => 'user_sessions#new', :as => :login, via: [:get, :post]
  match 'logout' => 'user_sessions#destroy', :as => :logout, via: [:get, :post]
  match 'home' => 'users#show', :as => :home, via: [:get, :post]

  root :to => 'user_sessions#new'
end

app/models/factura.rb
class Factura < ActiveRecord::Base
  belongs_to :cliente
  has_many :items, :as => :order, dependent: :destroy
  
  accepts_nested_attributes_for :cliente, :items
  
  validates :number, :uniqueness => true, :numericality => true
  validates :cliente, :presence => true
  
  before_validation :set_default_values
  before_save :calculate_subtotal
  after_initialize :set_default_values
  
  IMPUESTO = GlobalConfiguration.impuesto
  MSM_INFO = [ "Carretera del Morche 200", "El Morche , Malaga  29793", "Tel. 952968184, Fax 952968184", "VICTOR HUGO DE LOS SANTOS FORNI", "N.I.F. 54234379-B"]
  
  def total
    total = subtotal + impuesto_subtotal
  end
  
  def impuesto_subtotal
    (subtotal*impuesto/100.0).to_d.round(2, BigDecimal::ROUND_UP)
  end
  
  private
  def set_default_values
    self.number||= (Factura.maximum(:number) || 0)+1
    self.subtotal||= 0
    self.impuesto||=IMPUESTO
  end
  def calculate_subtotal
    self.subtotal = items.reduce(0) do |sum, item|
      sum + item.total
    end
  end
end

app/controllers/facturas_controller.rb
class FacturasController < InvoiceController
  def invoice
    :factura
  end
end

app/helpers/facturas_helper.rb
module FacturasHelper
end

app/views/facturas/edit.html.haml
= render :partial => 'invoice/edit', :locals => {:invoice => :factura}

app/views/facturas/index.html.haml
:javascript
  //localize dates
  $(document).ready(function (){
    $('.date').each( function(){
      date = $.datepicker.parseDate('yy-mm-dd', $(this).text().trim());
      $(this).text($.datepicker.formatDate($.datepicker.regional['es'].dateFormat, date));
    });
   });
  
#factura
  %h1 Listado de Facturas
  .todos
    %table
      %tr
        %th Numero
        %th Fecha
        %th Cliente
        %th{:class => 'todos_menu'}
        %th{:class => 'todos_menu'}
        %th{:class => 'todos_menu'}

      - @facturas.each do |factura|
        %tr
          %td
            = factura.number
          %td.date
            = factura.created_at
          %td
            = factura.cliente
          %td{:class => 'todos_menu'} 
            = link_to 'Ver', factura
          %td{:class => 'todos_menu'} 
            = link_to 'Editar', edit_factura_path(factura)
          %td{:class => 'todos_menu'} 
            = link_to 'Eliminar', factura, :confirm => '¿Estas seguro?', :method => :delete
  .piepagina
    = link_to 'Nueva Factura', new_factura_path

app/views/facturas/new.html.haml
= render :partial => 'invoice/new', :locals => {:invoice => :factura, :title => 'Nueva Factura'}

app/views/facturas/show.html.haml
= render :partial => 'invoice/show', :locals => {:invoice => :factura}