config/routes.rb
Tienda::Application.routes.draw do
  resources :presupuestos
  resources :facturas do
    get 'summary', on: :collection
  end
  resources :albarans
  resources :users, :only => :show
  resources :user_sessions, :only => [:new, :create, :destroy]
  
  match 'login' => 'user_sessions#new', :as => :login, via: [:get, :post]
  match 'logout' => 'user_sessions#destroy', :as => :logout, via: [:get, :post]
  match 'home' => 'users#show', :as => :home, via: [:get, :post]

  root :to => 'user_sessions#new'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    = stylesheet_link_tag 'application.css', :media => 'all',  "data-turbolinks-track" => true
    %title Tienda
    = javascript_include_tag :application, "data-turbolinks-track" => true
    = yield :javascript
    = csrf_meta_tag
    %meta{'http-equiv' => "Content-Type", :content => "text/html; charset=utf-8"}

  %body
    #home
      = link_to 'Home', home_path, {:id => 'icomenu'}
      %ul#menu    
        %li#albarans
          = nav_button_for :albarans, 'ALBARÁN', {:id => 'menu_albaran'}
          %ul{:id => 'albarans_options', :class => 'menu02'}
            %li
              = link_to 'NUEVO', new_albaran_path, :id => 'new_alb'
            %li
              = link_to 'TODOS', albarans_path, :id => 'index_albaran'
        %li#facturas
          = nav_button_for :facturas, 'FACTURA', {:id => 'menu_factura'}
          %ul{:id => 'factura_options', :class => 'menu02'}
            %li
              = link_to 'NUEVA', new_factura_path, :id => 'new_fact'
            %li
              = link_to 'TODAS', facturas_path, :id => 'index_factura'
        %li#presupuestos
          = nav_button_for :presupuestos, 'PRESUPUESTO', {:id => 'menu_presupuesto'}
          %ul{:id => 'presupuesto_options', :class => 'menu02'}
            %li
              = link_to 'NUEVO', new_presupuesto_path, :id => 'new_pres'
            %li
              = link_to 'TODOS', presupuestos_path, :id => 'index_presupuesto'
      = link_to 'Salir', logout_path, {:id => 'logout'}
    #homebkg
      #bkg
        = yield

app/views/layouts/user_sessions.html.haml
!!!
%html
  %head
    = stylesheet_link_tag 'application.css', :media => 'all',  "data-turbolinks-track" => true
    %title Tienda
    = javascript_include_tag :application, "data-turbolinks-track" => true
    = yield :javascript
    = csrf_meta_tag
    %meta{'http-equiv' => "Content-Type", :content => "text/html; charset=utf-8"}

  %body.bp
    .container
    = yield